language: node_js
sudo: false
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
  - "4"
script: "npm run travis"
after_script: "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
env:
  - REACT=0.13
  - REACT=0.14
before_script: "npm install -g npm@2; sh install-relevant-react.sh"
